export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ADD_PRODUCT = "ADD_PRODUCT"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
export const CHECKOUT = "CHECKOUT"
export const SET_PROFILE = "SET_PROFILE"
